<?php

return [ 
    "CSV_FILE_PATH" => env("CSV_FILE_PATH"),

    "WITHDRAW_FEE_FOR_BUSINESS_USER" => env("WITHDRAW_FEE_FOR_BUSINESS_USER"),
    "WITHDRAW_FEE_FOR_PRIVATE_USER" => env("WITHDRAW_FEE_FOR_PRIVATE_USER"),
    
    "DEPOSITE_FEE" => env("DEPOSITE_FEE"),
    "CHARGE_FREE_WITHDRAW_TRANSACTION_PER_WEEK" => env("CHARGE_FREE_WITHDRAW_TRANSACTION_PER_WEEK"),
    "CHARGE_FREE_WITHDRAW_AMOUNT_PER_WEEK" => env("CHARGE_FREE_WITHDRAW_AMOUNT_PER_WEEK"),
    
    "DEPOSITE" => "deposit",
    "WITHDRAW" => "withdraw",

    "USER_PRIVATE" => "private",
    "USER_BUSINESS" => "business",

    "OPERATION_DATE" => 0,
    "OPERATION_USER_IDENTITY" => 1,
    "OPERATION_USER_TYPE" => 2,
    "OPERATION_TYPE" => 3,
    "OPERATION_AMOUNT" => 4,
    "OPERATION_CURRENCY" => 5,

    "CURRENCY_EXCHANGE_API" => env("CURRENCY_EXCHANGE_API"),
    "BASE_CURRENCY" => env("BASE_CURRENCY"),
    "CURRENCY_DO_NOT_HAVE_DECIMAL" => "JPY",
];